import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Theme from "../Theme/Theme";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import BackToTop from "@/Components/BackToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Transunity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <Navbar />
          <div className="">{children}</div>
          <hr className="w-full h-1  bg-gray-200 border-0 rounded dark:bg-gray-700" />
          <Footer />

          <BackToTop />
        </Theme>
      </body>
    </html>
  );
}
